// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzH43EtOMeYIk0MPDur3FvSvagGwzfso',
    appId: '1:389948242204:web:8bb15f809c2db6d251e2d9',
    messagingSenderId: '389948242204',
    projectId: 'richard-petzy',
    authDomain: 'richard-petzy.firebaseapp.com',
    storageBucket: 'richard-petzy.firebasestorage.app',
    measurementId: 'G-HBYWRZDW8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF7KvW8OoqNz4IUKzJOSHONCmq2z5IEE0',
    appId: '1:389948242204:android:a04f7fc944d5165651e2d9',
    messagingSenderId: '389948242204',
    projectId: 'richard-petzy',
    storageBucket: 'richard-petzy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxMEtDxTkSTetMDFnXJOKyQMc7CuZAf8',
    appId: '1:389948242204:ios:57e5142b0fc7963051e2d9',
    messagingSenderId: '389948242204',
    projectId: 'richard-petzy',
    storageBucket: 'richard-petzy.firebasestorage.app',
    iosBundleId: 'com.example.riverpodGoRouterBoilerplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxMEtDxTkSTetMDFnXJOKyQMc7CuZAf8',
    appId: '1:389948242204:ios:57e5142b0fc7963051e2d9',
    messagingSenderId: '389948242204',
    projectId: 'richard-petzy',
    storageBucket: 'richard-petzy.firebasestorage.app',
    iosBundleId: 'com.example.riverpodGoRouterBoilerplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZzH43EtOMeYIk0MPDur3FvSvagGwzfso',
    appId: '1:389948242204:web:48c7adfad185960251e2d9',
    messagingSenderId: '389948242204',
    projectId: 'richard-petzy',
    authDomain: 'richard-petzy.firebaseapp.com',
    storageBucket: 'richard-petzy.firebasestorage.app',
    measurementId: 'G-G7GK54D4YN',
  );
}
